# Site settings
title: Echo's Blog
SEOTitle: 见贤思齐 | Echo's Blog
header-img: img/home-bg.jpg
email: yuandghn@gmail.com
description: "见贤思齐，见不贤而内自省。"
keyword: ""
url: "http://echoyuan.me"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'

timezone: Asia/Shanghai

# SNS settings
RSS: false
#zhihu_username:    yuandghn
github_username:    yuandghn

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","start.sh","yuandghn.github.io.iml"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Disqus settings
disqus_username: echoyuan-me

# NetEase cloud tie settings
#netease_cloud_tie: 'f6ed97fb3c034176b8d2344b36b041ff'

# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-100324645-1'            # Format: UA-xxxxxx-xx
ga_domain: echoyuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "凡事开窍太晚；<br/>人生无常，及时行乐。"
sidebar-avatar: /img/avatar-echo.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
#friends: [
 #   {
  #      title: "小琐的小碎",
   #     href: "http://sun0905.me"
    #}
#]
